import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getDisputeEvidence } from '../services/api';
import NavBar from '../components/NavBar';
import LoadingSpinner from '../components/LoadingSpinner';

/**
 * 争议证据包页面 — 打印友好的"文档"，商户直接 Print → Save as PDF 提交给发卡行。
 * Dispute evidence page: a print-friendly document. The merchant hits
 * Print → Save as PDF and submits it to the issuing bank; Download JSON
 * gives the machine-readable copy for payment-gateway dispute portals.
 *
 * 屏幕上文档渲染为深色应用里的一张"白纸"；打印时应用外壳（导航、按钮）通过
 * print:hidden 隐藏，只留白纸本身 —— 浏览器默认不打印背景色，深底白字会印成
 * 白底白字，所以文档必须黑字白底。
 * On screen the document is a sheet of "paper" inside the dark app; in print the
 * app chrome is hidden via print:hidden. The document itself must be dark-on-white:
 * browsers don't print background colors, so light-on-dark text would vanish.
 */
export default function DisputeEvidencePage() {
  const { orderId } = useParams();
  const navigate    = useNavigate();
  const [evidence, setEvidence] = useState(null);
  const [loading,  setLoading]  = useState(true);
  const [error,    setError]    = useState('');

  useEffect(() => {
    getDisputeEvidence(orderId)
      .then(setEvidence)
      .catch(() => setError('Could not load dispute evidence for this order.'))
      .finally(() => setLoading(false));
  }, [orderId]);

  function downloadJson() {
    const blob = new Blob([JSON.stringify(evidence, null, 2)], { type: 'application/json' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `dispute-evidence-${orderId}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const event = evidence?.event;
  const fmt = (ts) => (ts ? new Date(ts).toLocaleString() : '—');

  return (
    <div className="min-h-screen bg-dark-bg print:bg-white">
      <div className="print:hidden"><NavBar /></div>

      <div className="max-w-3xl mx-auto px-4 py-8 print:p-0 print:max-w-none">
        {/* 屏幕操作栏，打印时隐藏 / on-screen action bar, hidden in print */}
        <div className="flex items-center justify-between mb-6 print:hidden">
          <button
            onClick={() => navigate(`/orders/${orderId}`)}
            className="flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors"
          >
            ← Back to Order
          </button>
          {evidence && (
            <div className="flex gap-3">
              <button
                onClick={downloadJson}
                className="text-sm px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors"
              >
                ⬇ Download JSON
              </button>
              <button
                onClick={() => window.print()}
                className="text-sm px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg transition-colors"
              >
                🖨 Print / Save as PDF
              </button>
            </div>
          )}
        </div>

        {loading ? <LoadingSpinner /> : error ? (
          <div className="p-4 bg-red-500/10 border border-red-500/30 rounded-xl text-red-400">{error}</div>
        ) : evidence && (
          <div className="bg-white text-slate-900 rounded-xl print:rounded-none shadow-2xl print:shadow-none p-10 space-y-8">

            {/* ── Document header ── */}
            <header className="border-b-2 border-slate-900 pb-4">
              <p className="text-xs uppercase tracking-widest text-slate-500">FraudShield</p>
              <h1 className="text-2xl font-bold mt-1">Dispute Evidence Package</h1>
              <div className="mt-3 grid grid-cols-2 gap-x-8 gap-y-1 text-sm">
                <p><span className="text-slate-500">Order:</span> <span className="font-mono">{orderId}</span></p>
                <p><span className="text-slate-500">Generated:</span> {fmt(evidence.generatedAt)}</p>
                <p><span className="text-slate-500">Generated by:</span> {evidence.generatedBy}</p>
              </div>
            </header>

            {/* ── Integrity attestation ── */}
            <div className={`p-4 rounded-lg border text-sm ${
              evidence.chainValid
                ? 'bg-green-50 border-green-300 text-green-900'
                : 'bg-red-50 border-red-300 text-red-900'
            }`}>
              {evidence.chainValid ? (
                <>✔ <strong>Audit chain verified intact</strong> at generation time
                  ({evidence.chainRecordCount} records checked). The review decision below has
                  not been altered since it was recorded.</>
              ) : (
                <>⚠ <strong>Audit chain integrity check FAILED.</strong> The tamper-evident log
                  could not be verified — treat the audit records below with caution.</>
              )}
            </div>

            {/* ── 1. Order summary ── */}
            <section>
              <h2 className="text-sm font-bold uppercase tracking-wide border-b border-slate-300 pb-1 mb-3">
                1. Order Summary
              </h2>
              <dl className="grid grid-cols-2 gap-x-8 gap-y-2 text-sm">
                {[
                  ['Order ID',    event.orderId],
                  ['User ID',     event.userId],
                  ['Amount',      event.amount != null ? `$${event.amount.toFixed(2)}` : '—'],
                  ['IP Address',  event.ipAddress],
                  ['Device ID',   event.deviceId || '—'],
                  ['Ship To',     event.shippingAddress || '—'],
                  ['Bill To',     event.billingAddress || '—'],
                  ['Detected At', fmt(event.detectedAt)],
                ].map(([label, val]) => (
                  <div key={label} className="flex justify-between border-b border-dotted border-slate-200 pb-1">
                    <dt className="text-slate-500">{label}</dt>
                    <dd className="font-mono">{val}</dd>
                  </div>
                ))}
              </dl>
            </section>

            {/* ── 2. Automated risk assessment ── */}
            <section>
              <h2 className="text-sm font-bold uppercase tracking-wide border-b border-slate-300 pb-1 mb-3">
                2. Automated Risk Assessment
              </h2>
              <p className="text-sm mb-2">
                <span className="text-slate-500">Risk level:</span>{' '}
                <strong>{event.riskLevel}</strong>
                <span className="text-slate-500 ml-4">Risk score:</span>{' '}
                <strong>{((event.riskScore ?? 0) * 100).toFixed(0)}%</strong>
              </p>
              {event.triggeredRules?.length > 0 && (
                <p className="text-sm mb-2">
                  <span className="text-slate-500">Rules triggered:</span>{' '}
                  {event.triggeredRules.join(', ')}
                </p>
              )}
              {event.explanation && (
                <p className="text-sm bg-slate-50 border border-slate-200 rounded p-3">
                  {event.explanation}
                </p>
              )}
            </section>

            {/* ── 3. AI analysis (only when present) ── */}
            {event.aiEnhanced && (
              <section>
                <h2 className="text-sm font-bold uppercase tracking-wide border-b border-slate-300 pb-1 mb-3">
                  3. AI Analysis
                </h2>
                <p className="text-sm mb-2">
                  <span className="text-slate-500">AI risk level:</span>{' '}
                  <strong>{event.aiRiskLevel}</strong>
                  {event.aiConfidence != null && (
                    <><span className="text-slate-500 ml-4">Confidence:</span>{' '}
                      <strong>{(event.aiConfidence * 100).toFixed(0)}%</strong></>
                  )}
                  {event.aiRecommendation && (
                    <><span className="text-slate-500 ml-4">Recommendation:</span>{' '}
                      <strong>{event.aiRecommendation}</strong></>
                  )}
                </p>
                {event.aiReasoning && (
                  <p className="text-sm bg-slate-50 border border-slate-200 rounded p-3 mb-2">
                    {event.aiReasoning}
                  </p>
                )}
                {event.aiKeyFactors?.length > 0 && (
                  <p className="text-sm">
                    <span className="text-slate-500">Key factors:</span>{' '}
                    {event.aiKeyFactors.join(', ')}
                  </p>
                )}
              </section>
            )}

            {/* ── 4. Human review decision ── */}
            <section>
              <h2 className="text-sm font-bold uppercase tracking-wide border-b border-slate-300 pb-1 mb-3">
                {event.aiEnhanced ? '4' : '3'}. Human Review Decision
              </h2>
              {event.reviewStatus && event.reviewStatus !== 'PENDING_REVIEW' ? (
                <dl className="grid grid-cols-2 gap-x-8 gap-y-2 text-sm">
                  {[
                    ['Decision',    event.reviewStatus.replace('_', ' ')],
                    ['Reviewed by', event.reviewedBy],
                    ['Reviewed at', fmt(event.reviewedAt)],
                    ['Notes',       event.reviewNotes || '—'],
                  ].map(([label, val]) => (
                    <div key={label} className="flex justify-between border-b border-dotted border-slate-200 pb-1">
                      <dt className="text-slate-500">{label}</dt>
                      <dd className="font-medium text-right">{val}</dd>
                    </div>
                  ))}
                </dl>
              ) : (
                <p className="text-sm bg-amber-50 border border-amber-300 text-amber-900 rounded p-3">
                  ⚠ This order has not been reviewed yet. The evidence package carries more
                  weight once a reviewer records a decision.
                </p>
              )}
            </section>

            {/* ── 5. Tamper-evident audit records ── */}
            <section>
              <h2 className="text-sm font-bold uppercase tracking-wide border-b border-slate-300 pb-1 mb-3">
                {event.aiEnhanced ? '5' : '4'}. Tamper-Evident Audit Records
              </h2>
              {evidence.auditTrail?.length === 0 ? (
                <p className="text-sm text-slate-500">
                  No audit records exist for this order yet — records are created when a review
                  decision is submitted.
                </p>
              ) : (
                <div className="space-y-3">
                  {evidence.auditTrail.map((r) => (
                    <div key={r.id} className="text-sm border border-slate-200 rounded p-3">
                      <p>
                        <strong>{r.decision.replace('_', ' ')}</strong>
                        <span className="text-slate-500"> by </span>{r.reviewer}
                        <span className="text-slate-500"> on </span>{fmt(r.decidedAt)}
                      </p>
                      <p className="font-mono text-[10px] text-slate-500 break-all mt-1">
                        prev: {r.prevHash}
                      </p>
                      <p className="font-mono text-[10px] text-slate-700 break-all">
                        hash: {r.recordHash}
                      </p>
                    </div>
                  ))}
                </div>
              )}
              <p className="text-xs text-slate-500 mt-3 leading-relaxed">
                Each audit record carries an HMAC-SHA256 hash covering its own contents and the
                hash of the preceding record. Altering any historical record invalidates every
                subsequent hash, so the chain verification above attests that these decisions
                are recorded exactly as they were made.
              </p>
            </section>

            <footer className="border-t border-slate-300 pt-3 text-xs text-slate-400">
              Generated by FraudShield fraud detection system · {fmt(evidence.generatedAt)}
            </footer>
          </div>
        )}
      </div>
    </div>
  );
}
